### PR TITLE
Export upstream icons instead of hosting them here

### PR DESCRIPTION
**Pull request by Erick555**

### CODE REVIEW

**Comment by Erick555** [comment]
bot, build

**Comment by nedrichards** [comment]
This will have broken the app stores We have to have the icons visible and shipped in the app *before* the extra data is downloaded. You can overwrite them with the latest or better versions, but we need local copies of 64 and 128px ones in the correct place.

**Comment by Erick555** [comment]
Hm, but this is the same thing that spotify does: https://github.com/flathub/com.spotify.Client/blob/master/com.spotify.Client.json#L128 . 

Doesn't store icons come from there: https://github.com/flathub/com.elsevier.MendeleyDesktop/blob/master/com.elsevier.MendeleyDesktop.appdata.xml#L36 ?

**Comment by Erick555** [comment]
I checked on flathub.org and KDE Discover and mendeley icon is visible there.
https://flathub.org/apps/details/com.elsevier.MendeleyDesktop

**Comment by nedrichards** [comment]
They *can* do but it's much more fragile (apologies, I didn't realise we had remote icons in the appdata here). Remote icons were a thing we pushed at the beginning of flathub, when we believed we weren't allowed to host icons at all, but legal discussion led us to believe that this was something we could do for the purposes of advertising an application.

For now, this is fine - just keep an eye on it.

**Comment by Erick555** [comment]
Ok, thx for the info.

**Pull request merged**
