### PR TITLE
Update to 1.19.1

### PR DESCRIPTION
**Pull request by nedrichards**
This upgrades to KDE 5.11 and the upstream 1.19.1 release.

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by Erick555** [comment]
I didn't tested it yet but IIRC mendeley is build against qt 5.10 and newest version is 1.19.2

**Comment by Erick555** [comment]
I just tested this with runtime-version: 5.11 and mendeley 1.19.2 and it works! You have to re-login at startup. Viewing pdf works. I don't know if it's worth downgrading to runtime-version: 5.10.

**Comment by nedrichards** [comment]
I'll happily upgrade to 1.19.2 but I'm a bit reluctant over 5.10 given that the rest of that SDK is not maintained now that Qt 5.10 is end of life. Really awesome that it works! 

I've sent you an invitation to be a contributor here as you've been doing the maintence and testing (and greg is busy for the forseeable) and then you should have the ability to push commits to this branch, and merge when you're happy.

**Comment by Erick555** [comment]
@nedrichards where did you found release dates? https://github.com/flathub/com.elsevier.MendeleyDesktop/blob/1.19.1/com.elsevier.MendeleyDesktop.appdata.xml#L25

**Comment by nedrichards** [comment]
I genuinely can't remember for the 1.19.1, I don't actually think it was correct. The only thing you have to make sure of (aside from accuracy) is that the date is in the past). Oh, and also - you can use the bot, build command in comments here to kickoff test builds on https://flathub.org/builds

**Comment by Erick555** [comment]
bot, build

**Comment by Erick555** [comment]
I used date of creation files in mendeley archive. Test build succeded: https://flathub.org/builds/#/builders/31/builds/444

**Pull request merged**
